### PR TITLE
Fix context must be a dict

### PR DESCRIPTION
**Pull request by will-moore**
Simple fix for https://github.com/ome/prod-playbooks/pull/229#issuecomment-578705624

NB: haven't installed and tested the POST to send e-mail etc.
Just done the obvious code fix.

cc @manics @mtbc

### CODE REVIEW

**Comment by mtbc** [comment]
Now deployed at https://pub-omero.openmicroscopy.org/signup/
```
omero-signup==0.2.2.dev0
```

**Comment by joshmoore** [comment]
And is working?

**Review by manics — APPROVED** [review]
Works for me.

**Comment by joshmoore** [comment]
:+1: releasing as 0.2.2 then.

**Pull request merged**
