### PR TITLE
Django 3 2

### PR DESCRIPTION
**Pull request by will-moore**
To work with https://github.com/ome/omero-web/pull/356 

To test:
 - go to https://merge-ci.openmicroscopy.org/web/signup/
 - Fill in form and submit
 - You should get a response with login username and password
 - Login with those, should be in a group called `signup-test`

### CODE REVIEW

**Comment by pwalczysko** [comment]
This worked as described. A meesage was shown in browser with the new creds. Login was successful.
I suppose the email sending is not set up ? (I did not receive any email) cc @jburel 

All on merge-ci

**Comment by jburel** [comment]
The email notification was set-up to test the "forgot email" workflow so unless something else did not get set up

**Comment by will-moore** [comment]
I didn't enable e-mail sending in the signup config. Didn't know it was set-up.
I don't expect to find any issues with sending e-mails, but
I could add `omero.web.signup.email.enabled = True` to merge-ci?

**Comment by pwalczysko** [comment]
> I didn't enable e-mail sending in the signup config. Didn't know it was set-up. I don't expect to find any issues with sending e-mails, but I could add `omero.web.signup.email.enabled = True` to merge-ci?

I think it is a good idea to have it. We are constatnly getting demo...opy.org feedback saying "Did not get that email with creds". i guess it is caused by the firewall at recipient side, but it would be good to have the certainty that it works on our side.

**Comment by pwalczysko** [comment]
``Error: Invalid requestid: 41984e22-04af-4ba1-9cc6-dfab5e5b360f``

This might have been caused by the fact that the email address was used already once ? Anyway, on a second attempt, I am getting the following, see screenshot below ( I have cut the screenshot so that my email address is not visible).
I also received the email okay.

signup

**Review by pwalczysko — APPROVED** [review]

**Pull request merged**
