### PR TITLE
Py3 fixes

### PR DESCRIPTION
**Pull request by will-moore**
Fixes to run signup on omero-web 5.6.1 (django 1.11 and python 3).

### CODE REVIEW

**Comment by mtbc** [comment]
Now deployed at https://pub-omero.openmicroscopy.org/signup/.

**Comment by manics** [comment]
```
Traceback (most recent call last):

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero_signup/views.py", line 122, in post
    omeuser = self.create_account(user)

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero_signup/views.py", line 158, in create_account
    self._email_user(adminc.c, omeuser)

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero_signup/views.py", line 237, in _email_user
    failonerror=True, failontimeout=True)

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/clients.py", line 983, in submit
    closehandle=True)

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/clients.py", line 1002, in waitOnCmd
    callback.loop(loops, ms)  # Throw LockTimeout

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/callbacks.py", line 260, in loop
    5000, int(waited))

omero.LockTimeout: exception ::omero::LockTimeout
{
    serverStackTrace = None
    serverExceptionClass = None
    message = Command unfinished after 5.0 seconds
    backOff = 5000
    seconds = 5
}

<WSGIRequest: POST '/signup/'>
```

**Comment by manics** [comment]
Despite the error I received a `Your OMERO server login details` email

**Comment by joshmoore** [comment]
Can I propose we release this as a quick 0.2.1 and then follow-up with the timeout fix?

cc: @will-moore @manics

**Comment by joshmoore** [comment]
Taking that as a yes.

**Pull request merged**
